import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '../../components/Navbar/navbar'
import Footer from '../../components/Footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'WhyDesigns',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://use.typekit.net/wdu3vmy.css"/>
      </head>
      <body className={inter.className}>
        <NavBar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
